workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: macos_m1
    environment:
      groups:
        - default
      vars:
        NODE_VERSION: 22
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build Android APK
        script: |
          cd frontend/android
          ./gradlew assembleDebug
    artifacts:
      - frontend/android/app/build/outputs/apk/**/*.apk
