scripts:
  - name: Install dependencies
    script: |
      cd frontend
      npm install
  - name: Prebuild Android folder
    script: |
      cd frontend
      npx expo prebuild --platform android --clean
  - name: Build Android APK
    script: |
      cd frontend/android
      ./gradlew assembleDebug
