name: Deploy OTA Update
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Publish EAS Update
        env:
          EAS_PROJECT_ID: 'da7e8ad1-adbd-4341-9221-78c6702a848f'
        run: |
          cd frontend
          npx expo publish --non-interactive
